# redis 配置
singleServerConfig:
  idleConnectionTimeout: 10000
  pingTimeout: 1000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  subscriptionsPerConnection: 5
  sslEnableEndpointIdentification: true
  sslProvider: "JDK"
  password: "Admin888."
  pingConnectionInterval: 0
  keepAlive: false
  tcpNoDelay: false
  address: "redis://redis.dev.perfma-inc.net:6379"
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 32
  connectionPoolSize: 64
  database: 0
  dnsMonitoringInterval: 5000
threads: 0
nettyThreads: 0
codec:
  class: org.redisson.codec.FstCodec
referenceCodecProvider:
  class: org.redisson.codec.DefaultReferenceCodecProvider
referenceEnabled: true
transportMode: "NIO"
lockWatchdogTimeout: 30000
keepPubSubOrder: true
useScriptCache: false
addressResolverGroupFactory:
   class: org.redisson.connection.DnsAddressResolverGroupFactory
useLinuxNativeEpoll: false